# test trigger

trigger:
  batch: false
  branches:
    include: ["master"]
  paths:
    include:
      [
        "azure-pipelines.sycamorememphis-org.yaml",
        "docker-compose.sycamorememphis-org.yml",
      ]

pr: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: CopyFiles@2
    displayName: "stage files"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)"
      Contents: |
        docker-compose.*.yml
      TargetFolder: "$(Build.ArtifactStagingDirectory)"
      CleanTargetFolder: true
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: "publish files"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
