trigger:
  batch: false
  branches:
    include: ["main"]
  paths:
    include:
      ["azure-pipelines.nginx.yaml", "nginx/*", "docker-compose.nginx.yml"]

pr: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: CopyFiles@2
    displayName: "stage files"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)"
      Contents: |
        nginx/**
        docker-compose.*.yml
      TargetFolder: "$(Build.ArtifactStagingDirectory)"
      CleanTargetFolder: true
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: "publish files"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
