version: "3.7"

services:
  wp_collinmbarrett-com:
    image: wordpress:fpm-alpine
    restart: always
    networks:
      - reverse-proxy
      - collinmbarrett-com
    depends_on:
      - mariadb_collinmbarrett-com
      - redis_collinmbarrett-com
    volumes:
      - collinmbarrett-com_files:/var/www/html

  redis_collinmbarrett-com:
    image: redis:32bit-stretch
    restart: always
    networks:
      - collinmbarrett-com
    depends_on:
      - mariadb_collinmbarrett-com
    volumes:
      - collinmbarrett-com_cache:/data
    command: ["redis-server", "--appendonly", "yes"]

  mariadb_collinmbarrett-com:
    image: mariadb:latest
    restart: always
    networks:
      - collinmbarrett-com
    volumes:
      - collinmbarrett-com_data:/var/lib/mysql

  wp-cli_collinmbarrett-com:
    image: wordpress:cli
    networks:
      - collinmbarrett-com
    volumes:
      - collinmbarrett-com_files:/var/www/html

networks:
  reverse-proxy:
    external:
      name: wp-host_reverse-proxy
  collinmbarrett-com:

volumes:
  collinmbarrett-com_files:
  collinmbarrett-com_cache:
  collinmbarrett-com_data:
