version: "3.7"

services:
  wp_jennythebaker-com:
    image: wordpress:fpm-alpine
    restart: always
    networks:
      - reverse-proxy
      - jennythebaker-com
    depends_on:
      - mariadb_jennythebaker-com
      - redis_jennythebaker-com
    volumes:
      - jennythebaker-com_files:/var/www/html

  redis_jennythebaker-com:
    image: redis:32bit-stretch
    restart: always
    networks:
      - jennythebaker-com
    depends_on:
      - mariadb_jennythebaker-com
    volumes:
      - jennythebaker-com_cache:/data
    command: ["redis-server", "--appendonly", "yes"]

  mariadb_jennythebaker-com:
    image: mariadb:10
    restart: always
    networks:
      - jennythebaker-com
    volumes:
      - jennythebaker-com_data:/var/lib/mysql

  wp-cli_jennythebaker-com:
    image: wordpress:cli-php7.3
    networks:
      - jennythebaker-com
    volumes:
      - jennythebaker-com_files:/var/www/html

networks:
  reverse-proxy:
    external:
      name: wp-host_reverse-proxy
  jennythebaker-com:

volumes:
  jennythebaker-com_files:
  jennythebaker-com_cache:
  jennythebaker-com_data:
