version: "3.7"

services:
  wp_sycamorememphis-org:
    image: wordpress:fpm-alpine
    restart: always
    networks:
      - reverse-proxy
      - sycamorememphis-org
    depends_on:
      - mariadb_sycamorememphis-org
      - redis_sycamorememphis-org
    volumes:
      - sycamorememphis-org_files:/var/www/html

  redis_sycamorememphis-org:
    image: redis:32bit
    restart: always
    networks:
      - sycamorememphis-org
    depends_on:
      - mariadb_sycamorememphis-org
    volumes:
      - sycamorememphis-org_cache:/data
    command: ["redis-server", "--appendonly", "yes"]

  mariadb_sycamorememphis-org:
    image: mariadb:latest
    restart: always
    networks:
      - sycamorememphis-org
    volumes:
      - sycamorememphis-org_data:/var/lib/mysql

  wp-cli_sycamorememphis-org:
    image: wordpress:cli
    networks:
      - sycamorememphis-org
    volumes:
      - sycamorememphis-org_files:/var/www/html

networks:
  reverse-proxy:
    external:
      name: wp-host_reverse-proxy
  sycamorememphis-org:

volumes:
  sycamorememphis-org_files:
  sycamorememphis-org_cache:
  sycamorememphis-org_data:
