version: "3.7"

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "443:443"
    networks:
      - reverse-proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/svr-includes:/etc/nginx/svr-includes:ro
      - ~/cert:/etc/nginx/cert:ro
      - jennythebaker-com_files:/var/www/jennythebaker-com:ro
    depends_on:
      - wp_jennythebaker-com

networks:
  reverse-proxy:
    name: wp-host_reverse-proxy

volumes:
  jennythebaker-com_files:
    external:
      name: wp-host_jennythebaker-com_files
